// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hrtf.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HRTF struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorageId            string               `protobuf:"bytes,3,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Filename             string               `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	License              string               `protobuf:"bytes,5,opt,name=license,proto3" json:"license,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HRTF) Reset()         { *m = HRTF{} }
func (m *HRTF) String() string { return proto.CompactTextString(m) }
func (*HRTF) ProtoMessage()    {}
func (*HRTF) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{0}
}

func (m *HRTF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HRTF.Unmarshal(m, b)
}
func (m *HRTF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HRTF.Marshal(b, m, deterministic)
}
func (m *HRTF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HRTF.Merge(m, src)
}
func (m *HRTF) XXX_Size() int {
	return xxx_messageInfo_HRTF.Size(m)
}
func (m *HRTF) XXX_DiscardUnknown() {
	xxx_messageInfo_HRTF.DiscardUnknown(m)
}

var xxx_messageInfo_HRTF proto.InternalMessageInfo

func (m *HRTF) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HRTF) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *HRTF) GetStorageId() string {
	if m != nil {
		return m.StorageId
	}
	return ""
}

func (m *HRTF) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *HRTF) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *HRTF) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *HRTF) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateHRTFRequest struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHRTFRequest) Reset()         { *m = CreateHRTFRequest{} }
func (m *CreateHRTFRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHRTFRequest) ProtoMessage()    {}
func (*CreateHRTFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{1}
}

func (m *CreateHRTFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHRTFRequest.Unmarshal(m, b)
}
func (m *CreateHRTFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHRTFRequest.Marshal(b, m, deterministic)
}
func (m *CreateHRTFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHRTFRequest.Merge(m, src)
}
func (m *CreateHRTFRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHRTFRequest.Size(m)
}
func (m *CreateHRTFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHRTFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHRTFRequest proto.InternalMessageInfo

func (m *CreateHRTFRequest) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type CreateHRTFResponse struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHRTFResponse) Reset()         { *m = CreateHRTFResponse{} }
func (m *CreateHRTFResponse) String() string { return proto.CompactTextString(m) }
func (*CreateHRTFResponse) ProtoMessage()    {}
func (*CreateHRTFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{2}
}

func (m *CreateHRTFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHRTFResponse.Unmarshal(m, b)
}
func (m *CreateHRTFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHRTFResponse.Marshal(b, m, deterministic)
}
func (m *CreateHRTFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHRTFResponse.Merge(m, src)
}
func (m *CreateHRTFResponse) XXX_Size() int {
	return xxx_messageInfo_CreateHRTFResponse.Size(m)
}
func (m *CreateHRTFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHRTFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHRTFResponse proto.InternalMessageInfo

func (m *CreateHRTFResponse) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type GetHRTFRequest struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHRTFRequest) Reset()         { *m = GetHRTFRequest{} }
func (m *GetHRTFRequest) String() string { return proto.CompactTextString(m) }
func (*GetHRTFRequest) ProtoMessage()    {}
func (*GetHRTFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{3}
}

func (m *GetHRTFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHRTFRequest.Unmarshal(m, b)
}
func (m *GetHRTFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHRTFRequest.Marshal(b, m, deterministic)
}
func (m *GetHRTFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHRTFRequest.Merge(m, src)
}
func (m *GetHRTFRequest) XXX_Size() int {
	return xxx_messageInfo_GetHRTFRequest.Size(m)
}
func (m *GetHRTFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHRTFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHRTFRequest proto.InternalMessageInfo

func (m *GetHRTFRequest) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type GetHRTFResponse struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHRTFResponse) Reset()         { *m = GetHRTFResponse{} }
func (m *GetHRTFResponse) String() string { return proto.CompactTextString(m) }
func (*GetHRTFResponse) ProtoMessage()    {}
func (*GetHRTFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{4}
}

func (m *GetHRTFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHRTFResponse.Unmarshal(m, b)
}
func (m *GetHRTFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHRTFResponse.Marshal(b, m, deterministic)
}
func (m *GetHRTFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHRTFResponse.Merge(m, src)
}
func (m *GetHRTFResponse) XXX_Size() int {
	return xxx_messageInfo_GetHRTFResponse.Size(m)
}
func (m *GetHRTFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHRTFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHRTFResponse proto.InternalMessageInfo

func (m *GetHRTFResponse) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type UpdateHRTFRequest struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHRTFRequest) Reset()         { *m = UpdateHRTFRequest{} }
func (m *UpdateHRTFRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateHRTFRequest) ProtoMessage()    {}
func (*UpdateHRTFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{5}
}

func (m *UpdateHRTFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHRTFRequest.Unmarshal(m, b)
}
func (m *UpdateHRTFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHRTFRequest.Marshal(b, m, deterministic)
}
func (m *UpdateHRTFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHRTFRequest.Merge(m, src)
}
func (m *UpdateHRTFRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateHRTFRequest.Size(m)
}
func (m *UpdateHRTFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHRTFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHRTFRequest proto.InternalMessageInfo

func (m *UpdateHRTFRequest) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type UpdateHRTFResponse struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateHRTFResponse) Reset()         { *m = UpdateHRTFResponse{} }
func (m *UpdateHRTFResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateHRTFResponse) ProtoMessage()    {}
func (*UpdateHRTFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{6}
}

func (m *UpdateHRTFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateHRTFResponse.Unmarshal(m, b)
}
func (m *UpdateHRTFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateHRTFResponse.Marshal(b, m, deterministic)
}
func (m *UpdateHRTFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateHRTFResponse.Merge(m, src)
}
func (m *UpdateHRTFResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateHRTFResponse.Size(m)
}
func (m *UpdateHRTFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateHRTFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateHRTFResponse proto.InternalMessageInfo

func (m *UpdateHRTFResponse) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type DeleteHRTFRequest struct {
	Hrtf                 *HRTF    `protobuf:"bytes,1,opt,name=hrtf,proto3" json:"hrtf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHRTFRequest) Reset()         { *m = DeleteHRTFRequest{} }
func (m *DeleteHRTFRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHRTFRequest) ProtoMessage()    {}
func (*DeleteHRTFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{7}
}

func (m *DeleteHRTFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHRTFRequest.Unmarshal(m, b)
}
func (m *DeleteHRTFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHRTFRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHRTFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHRTFRequest.Merge(m, src)
}
func (m *DeleteHRTFRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHRTFRequest.Size(m)
}
func (m *DeleteHRTFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHRTFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHRTFRequest proto.InternalMessageInfo

func (m *DeleteHRTFRequest) GetHrtf() *HRTF {
	if m != nil {
		return m.Hrtf
	}
	return nil
}

type DeleteHRTFResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHRTFResponse) Reset()         { *m = DeleteHRTFResponse{} }
func (m *DeleteHRTFResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteHRTFResponse) ProtoMessage()    {}
func (*DeleteHRTFResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{8}
}

func (m *DeleteHRTFResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHRTFResponse.Unmarshal(m, b)
}
func (m *DeleteHRTFResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHRTFResponse.Marshal(b, m, deterministic)
}
func (m *DeleteHRTFResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHRTFResponse.Merge(m, src)
}
func (m *DeleteHRTFResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteHRTFResponse.Size(m)
}
func (m *DeleteHRTFResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHRTFResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHRTFResponse proto.InternalMessageInfo

func (m *DeleteHRTFResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type ListHRTFsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHRTFsRequest) Reset()         { *m = ListHRTFsRequest{} }
func (m *ListHRTFsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHRTFsRequest) ProtoMessage()    {}
func (*ListHRTFsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{9}
}

func (m *ListHRTFsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHRTFsRequest.Unmarshal(m, b)
}
func (m *ListHRTFsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHRTFsRequest.Marshal(b, m, deterministic)
}
func (m *ListHRTFsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHRTFsRequest.Merge(m, src)
}
func (m *ListHRTFsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHRTFsRequest.Size(m)
}
func (m *ListHRTFsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHRTFsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHRTFsRequest proto.InternalMessageInfo

type ListHRTFsResponse struct {
	Hrtfs                []*HRTF  `protobuf:"bytes,1,rep,name=hrtfs,proto3" json:"hrtfs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHRTFsResponse) Reset()         { *m = ListHRTFsResponse{} }
func (m *ListHRTFsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHRTFsResponse) ProtoMessage()    {}
func (*ListHRTFsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4dc84056232f464, []int{10}
}

func (m *ListHRTFsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHRTFsResponse.Unmarshal(m, b)
}
func (m *ListHRTFsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHRTFsResponse.Marshal(b, m, deterministic)
}
func (m *ListHRTFsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHRTFsResponse.Merge(m, src)
}
func (m *ListHRTFsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHRTFsResponse.Size(m)
}
func (m *ListHRTFsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHRTFsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHRTFsResponse proto.InternalMessageInfo

func (m *ListHRTFsResponse) GetHrtfs() []*HRTF {
	if m != nil {
		return m.Hrtfs
	}
	return nil
}

func init() {
	proto.RegisterType((*HRTF)(nil), "api.HRTF")
	proto.RegisterType((*CreateHRTFRequest)(nil), "api.CreateHRTFRequest")
	proto.RegisterType((*CreateHRTFResponse)(nil), "api.CreateHRTFResponse")
	proto.RegisterType((*GetHRTFRequest)(nil), "api.GetHRTFRequest")
	proto.RegisterType((*GetHRTFResponse)(nil), "api.GetHRTFResponse")
	proto.RegisterType((*UpdateHRTFRequest)(nil), "api.UpdateHRTFRequest")
	proto.RegisterType((*UpdateHRTFResponse)(nil), "api.UpdateHRTFResponse")
	proto.RegisterType((*DeleteHRTFRequest)(nil), "api.DeleteHRTFRequest")
	proto.RegisterType((*DeleteHRTFResponse)(nil), "api.DeleteHRTFResponse")
	proto.RegisterType((*ListHRTFsRequest)(nil), "api.ListHRTFsRequest")
	proto.RegisterType((*ListHRTFsResponse)(nil), "api.ListHRTFsResponse")
}

func init() { proto.RegisterFile("hrtf.proto", fileDescriptor_d4dc84056232f464) }

var fileDescriptor_d4dc84056232f464 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0x6f, 0xda, 0x40,
	0x10, 0x85, 0x65, 0x43, 0x70, 0x3c, 0x48, 0x69, 0xd9, 0xb6, 0x89, 0x65, 0x29, 0x4a, 0xe4, 0x53,
	0x4e, 0xa6, 0x72, 0x72, 0x69, 0x25, 0x0e, 0x51, 0xab, 0xb6, 0x91, 0x7a, 0x32, 0xf4, 0x8c, 0x8c,
	0x3d, 0xd0, 0x95, 0x0c, 0x76, 0xbd, 0xeb, 0xfe, 0xba, 0xfe, 0xb2, 0x9e, 0xa2, 0x1d, 0xaf, 0x8d,
	0xc1, 0x48, 0xc0, 0x71, 0xde, 0xcc, 0xb7, 0x6f, 0xfc, 0x06, 0x00, 0x7e, 0x17, 0x72, 0xe9, 0xe7,
	0x45, 0x26, 0x33, 0xd6, 0x8b, 0x72, 0xee, 0xde, 0xad, 0xb2, 0x6c, 0x95, 0xe2, 0x98, 0xa4, 0x45,
	0xb9, 0x1c, 0x4b, 0xbe, 0x46, 0x21, 0xa3, 0x75, 0x5e, 0x4d, 0x79, 0xff, 0x0d, 0xe8, 0xff, 0x08,
	0x67, 0xdf, 0xd8, 0x15, 0x98, 0x3c, 0x71, 0x8c, 0x7b, 0xe3, 0xc1, 0x0e, 0x4d, 0x9e, 0xb0, 0x1b,
	0xb0, 0x4a, 0x81, 0xc5, 0x9c, 0x27, 0x8e, 0x49, 0xe2, 0x40, 0x95, 0x2f, 0x09, 0xbb, 0x05, 0x10,
	0x32, 0x2b, 0xa2, 0x15, 0xaa, 0x5e, 0x8f, 0x7a, 0xb6, 0x56, 0x5e, 0x12, 0xe6, 0xc2, 0xe5, 0x92,
	0xa7, 0xb8, 0x89, 0xd6, 0xe8, 0xf4, 0xa9, 0xd9, 0xd4, 0xcc, 0x01, 0x2b, 0xe5, 0x31, 0x6e, 0x04,
	0x3a, 0x17, 0xd4, 0xaa, 0x4b, 0xf6, 0x09, 0x20, 0x2e, 0x30, 0x92, 0x98, 0xcc, 0x23, 0xe9, 0x0c,
	0xee, 0x8d, 0x87, 0x61, 0xe0, 0xfa, 0xd5, 0xf2, 0x7e, 0xbd, 0xbc, 0x3f, 0xab, 0x97, 0x0f, 0x6d,
	0x3d, 0xfd, 0x2c, 0x15, 0x5a, 0xe6, 0x49, 0x8d, 0x5a, 0xc7, 0x51, 0x3d, 0xfd, 0x2c, 0xbd, 0x00,
	0x46, 0x5f, 0xe8, 0x1d, 0x95, 0x40, 0x88, 0x7f, 0x4a, 0x14, 0x92, 0xdd, 0x42, 0x5f, 0xa5, 0x48,
	0x51, 0x0c, 0x03, 0xdb, 0x8f, 0x72, 0xee, 0x53, 0x9f, 0x64, 0xef, 0x11, 0x58, 0x9b, 0x11, 0x79,
	0xa6, 0xf6, 0x3f, 0x02, 0x8d, 0xe1, 0xea, 0x3b, 0xca, 0x33, 0x5c, 0x3e, 0xc2, 0x9b, 0x06, 0x38,
	0xcd, 0x22, 0x80, 0xd1, 0x2f, 0xfa, 0xb0, 0xf3, 0xbe, 0xa5, 0xcd, 0x9c, 0x6c, 0xf4, 0x15, 0x53,
	0x3c, 0xd7, 0xa8, 0xcd, 0x34, 0x46, 0xc0, 0xc5, 0x5c, 0x94, 0x71, 0x8c, 0x42, 0x10, 0x7a, 0x19,
	0xda, 0x5c, 0x4c, 0x2b, 0xc1, 0x63, 0xf0, 0xf6, 0x27, 0x17, 0x14, 0x82, 0xd0, 0x3e, 0xde, 0x13,
	0x8c, 0x5a, 0x9a, 0x7e, 0xe7, 0x0e, 0x2e, 0x94, 0x8b, 0x7a, 0xa2, 0xb7, 0xeb, 0x5e, 0xe9, 0xc1,
	0x3f, 0x13, 0x86, 0xaa, 0x9e, 0x62, 0xf1, 0x97, 0xc7, 0xc8, 0x26, 0x00, 0xdb, 0x1b, 0xb2, 0x6b,
	0x9a, 0xef, 0xfc, 0x10, 0xdc, 0x9b, 0x8e, 0xae, 0xfd, 0x9e, 0xc0, 0xd2, 0xc7, 0x61, 0xef, 0x68,
	0x66, 0xf7, 0xb6, 0xee, 0xfb, 0x5d, 0x51, 0x53, 0x13, 0x80, 0x6d, 0xd8, 0xda, 0xb4, 0x73, 0x31,
	0x6d, 0x7a, 0xe0, 0x2a, 0x13, 0x80, 0x6d, 0x84, 0x1a, 0xef, 0xdc, 0x41, 0xe3, 0x07, 0xb2, 0xfe,
	0x0c, 0x76, 0x13, 0x1c, 0xfb, 0x40, 0x53, 0xfb, 0xe1, 0xba, 0xd7, 0xfb, 0x72, 0xc5, 0x2e, 0x06,
	0xf4, 0x2f, 0x7a, 0x7c, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x13, 0x2d, 0xd4, 0x5e, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HRTFServiceClient is the client API for HRTFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HRTFServiceClient interface {
	CreateHRTF(ctx context.Context, in *CreateHRTFRequest, opts ...grpc.CallOption) (*CreateHRTFResponse, error)
	GetHRTF(ctx context.Context, in *GetHRTFRequest, opts ...grpc.CallOption) (*GetHRTFResponse, error)
	UpdateHRTF(ctx context.Context, in *UpdateHRTFRequest, opts ...grpc.CallOption) (*UpdateHRTFResponse, error)
	DeleteHRTF(ctx context.Context, in *DeleteHRTFRequest, opts ...grpc.CallOption) (*DeleteHRTFResponse, error)
	ListHRTFs(ctx context.Context, in *ListHRTFsRequest, opts ...grpc.CallOption) (*ListHRTFsResponse, error)
}

type hRTFServiceClient struct {
	cc *grpc.ClientConn
}

func NewHRTFServiceClient(cc *grpc.ClientConn) HRTFServiceClient {
	return &hRTFServiceClient{cc}
}

func (c *hRTFServiceClient) CreateHRTF(ctx context.Context, in *CreateHRTFRequest, opts ...grpc.CallOption) (*CreateHRTFResponse, error) {
	out := new(CreateHRTFResponse)
	err := c.cc.Invoke(ctx, "/api.HRTFService/CreateHRTF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hRTFServiceClient) GetHRTF(ctx context.Context, in *GetHRTFRequest, opts ...grpc.CallOption) (*GetHRTFResponse, error) {
	out := new(GetHRTFResponse)
	err := c.cc.Invoke(ctx, "/api.HRTFService/GetHRTF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hRTFServiceClient) UpdateHRTF(ctx context.Context, in *UpdateHRTFRequest, opts ...grpc.CallOption) (*UpdateHRTFResponse, error) {
	out := new(UpdateHRTFResponse)
	err := c.cc.Invoke(ctx, "/api.HRTFService/UpdateHRTF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hRTFServiceClient) DeleteHRTF(ctx context.Context, in *DeleteHRTFRequest, opts ...grpc.CallOption) (*DeleteHRTFResponse, error) {
	out := new(DeleteHRTFResponse)
	err := c.cc.Invoke(ctx, "/api.HRTFService/DeleteHRTF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hRTFServiceClient) ListHRTFs(ctx context.Context, in *ListHRTFsRequest, opts ...grpc.CallOption) (*ListHRTFsResponse, error) {
	out := new(ListHRTFsResponse)
	err := c.cc.Invoke(ctx, "/api.HRTFService/ListHRTFs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HRTFServiceServer is the server API for HRTFService service.
type HRTFServiceServer interface {
	CreateHRTF(context.Context, *CreateHRTFRequest) (*CreateHRTFResponse, error)
	GetHRTF(context.Context, *GetHRTFRequest) (*GetHRTFResponse, error)
	UpdateHRTF(context.Context, *UpdateHRTFRequest) (*UpdateHRTFResponse, error)
	DeleteHRTF(context.Context, *DeleteHRTFRequest) (*DeleteHRTFResponse, error)
	ListHRTFs(context.Context, *ListHRTFsRequest) (*ListHRTFsResponse, error)
}

// UnimplementedHRTFServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHRTFServiceServer struct {
}

func (*UnimplementedHRTFServiceServer) CreateHRTF(ctx context.Context, req *CreateHRTFRequest) (*CreateHRTFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHRTF not implemented")
}
func (*UnimplementedHRTFServiceServer) GetHRTF(ctx context.Context, req *GetHRTFRequest) (*GetHRTFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHRTF not implemented")
}
func (*UnimplementedHRTFServiceServer) UpdateHRTF(ctx context.Context, req *UpdateHRTFRequest) (*UpdateHRTFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHRTF not implemented")
}
func (*UnimplementedHRTFServiceServer) DeleteHRTF(ctx context.Context, req *DeleteHRTFRequest) (*DeleteHRTFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHRTF not implemented")
}
func (*UnimplementedHRTFServiceServer) ListHRTFs(ctx context.Context, req *ListHRTFsRequest) (*ListHRTFsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHRTFs not implemented")
}

func RegisterHRTFServiceServer(s *grpc.Server, srv HRTFServiceServer) {
	s.RegisterService(&_HRTFService_serviceDesc, srv)
}

func _HRTFService_CreateHRTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHRTFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRTFServiceServer).CreateHRTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HRTFService/CreateHRTF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRTFServiceServer).CreateHRTF(ctx, req.(*CreateHRTFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HRTFService_GetHRTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHRTFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRTFServiceServer).GetHRTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HRTFService/GetHRTF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRTFServiceServer).GetHRTF(ctx, req.(*GetHRTFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HRTFService_UpdateHRTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHRTFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRTFServiceServer).UpdateHRTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HRTFService/UpdateHRTF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRTFServiceServer).UpdateHRTF(ctx, req.(*UpdateHRTFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HRTFService_DeleteHRTF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHRTFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRTFServiceServer).DeleteHRTF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HRTFService/DeleteHRTF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRTFServiceServer).DeleteHRTF(ctx, req.(*DeleteHRTFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HRTFService_ListHRTFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHRTFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRTFServiceServer).ListHRTFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HRTFService/ListHRTFs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRTFServiceServer).ListHRTFs(ctx, req.(*ListHRTFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HRTFService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HRTFService",
	HandlerType: (*HRTFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHRTF",
			Handler:    _HRTFService_CreateHRTF_Handler,
		},
		{
			MethodName: "GetHRTF",
			Handler:    _HRTFService_GetHRTF_Handler,
		},
		{
			MethodName: "UpdateHRTF",
			Handler:    _HRTFService_UpdateHRTF_Handler,
		},
		{
			MethodName: "DeleteHRTF",
			Handler:    _HRTFService_DeleteHRTF_Handler,
		},
		{
			MethodName: "ListHRTFs",
			Handler:    _HRTFService_ListHRTFs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hrtf.proto",
}
