CREATE DATABASE IF NOT EXISTS microservices;

CREATE TABLE IF NOT EXISTS microservices.users (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY UNIQUE,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    remember_token VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS microservices.hrtfs (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY UNIQUE,
    user_id INT NOT NULL,
    FOREIGN KEY fk_hrtfs_user_id (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    storage_id VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    license VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
